# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-27 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170327_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelTable(
            name='city',
            table=None,
        ),
    ]
