# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-27 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170327_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tel',
            field=models.CharField(default=3423, max_length=16, verbose_name='Тел.номер'),
            preserve_default=False,
        ),
    ]
