# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='city',
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=150, null=True, verbose_name='Транслит'),
        ),
    ]
